sudo: false
language: node_js
node_js: "10"

services:
  - xvfb

before_install:
- rm -rf node_modules
- npm install -g yarn

install:
  - yarn

jobs:
  include:
  - stage: Testing
    script: yarn test
    name: "Unit test"  
  - script: yarn build
    name: "Execute  build"
